services:
  - type: web
    name: nivalis-bot
    env: python
    buildCommand: "pip install -r pyproject.toml"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT web:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: nivalis-db
          property: connectionString
    autoDeploy: false

databases:
  - name: nivalis-db
    databaseName: nivalis
    user: nivalis